name: Superheroes
version: ${version}
main: me.xemor.superheroes.Superheroes
api-version: 1.16
authors: [Xemor_]
softdepend: [SkillsLibrary2, WorldGuard]
folia-supported: true
description: Adds superheroes to your world - these can be customized completely and are extremely modular.
libraries:
  - "com.fasterxml.jackson.core:jackson-core:2.18.0"
  - "com.fasterxml.jackson.core:jackson-databind:2.18.2"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.7.0"
commands:
  hero:
    description: The root command of all of the commands within Superheroes
    usage: /hero <hero> <name>
permissions:
  superheroes.hero:
    description: Allows them to use /hero
    default: op
  superheroes.hero.reroll:
    description: Allows them to use /reroll
    default: op
  superheroes.hero.select.others:
    description: Allows them to use /hero on other people
    default: op
  superheroes.hero.select.bypasscooldown:
    description: Allows them to use /hero regardless of whether it is on cooldown or not
    default: op
  superheroes.notify:
    description: Get informed about new updates to the Superheroes plugin!
    default: op
  superheroes.hero.check:
    description: Allows the user to check what their own hero is
    default: true
  superheroes.hero.check.others:
    description: Allows the user to check what other people's hero is
    default: op
  superheroes.hero.reload:
    description: Reloads the plugin
    default: op
  superheroes.hero.import:
    description: Imports from the export file into your current database
    default: op
  superheroes.hero.export:
    description: Exports the current database to a YAML file
    default: op