package me.xemor.superheroes2.skills;

public enum Skill {

    POTIONEFFECT, PHASE, STRONGMAN, INSTANTBREAK, LIGHT, NOHUNGER, ELECTRIFIED, SLIME, SNEAKINGPOTION, AURA, EGGLAYER, WALKER, PICKPOCKET;

}
