package me.xemor.superheroes2.skills;

public enum Skill {

    POTIONEFFECT, PHASE, STRONGMAN, CRAFTING, SLAM, ERASER, INSTANTBREAK, LIGHT, NOHUNGER, DAMAGERESISTANCE, SLIME, SNEAKINGPOTION, AURA, EGGLAYER, WALKER, PICKPOCKET;

}
