package me.xemor.superheroes2.skills;

public enum Skill {

    POTIONEFFECT, SUMMON, PHASE, STRONGMAN, CRAFTING, SLAM, ERASER, TELEPORT, INSTANTBREAK, LIGHT, NOHUNGER, DAMAGERESISTANCE, SLIME, SNEAKINGPOTION, AURA, EGGLAYER, WALKER, PICKPOCKET;

}
